var request = require('request');
var async = require('async');
var host = 'http://a3coreint02.dev.activenetwork.com';

var urls = [
	host + '/running/articles/how-to-boost-your-motivation-to-run',
	host + '/triathlon/articles/how-triathletes-can-stay-hydrated-on-race-day',
	host + '/fitness/articles/how-to-play-beach-volleyball',
	host + '/fitness/articles/how-to-build-core-strength-with-the-windshield-wiper-drill',
	host + '/fitness/articles/balance-ball-total-body-workout',
	host + '/outdoors/articles/how-to-build-a-fire-pit',
	host + '/outdoors/articles/how-to-choose-a-camping-spot-on-a-road-trip',
	host + '/fitness/articles/breathe-break-up-with-your-gym-and-train-like-a-pro-surfer',
	host + '/fitness/articles/3-exercises-to-do-at-your-desk',
	host + '/running/articles/4-post-run-stretches-for-runners',
	host + '/fitness/articles/obstacle-course-race-training-squats',
	host + '/fitness/articles/office-workouts-to-improve-your-fitness',
	host + '/running/articles/3-steps-to-acing-your-fall-5k',
	host + '/running/articles/marathon-tips-for-running-a-negative-split',
	host + '/fitness/articles/off-hill-training-tips-from-a-pro-freeskier',
	host + '/fitness/articles/neck-and-shoulder-positions-for-pilates-exercises',
	host + '/running/articles/video-tips-for-advanced-runners',
	host + '/running/articles/how-marathoners-can-prevent-achilles-tendonitis',
	host + '/parenting-and-family/articles/family-fitness-fun-exercises-for-kids',
	host + '/tennis/articles/how-to-improve-your-return-of-serve',
	host + '/fitness/articles/how-to-tone-your-arms-like-a-hollywood-celeb',
	host + '/running/articles/video-how-to-run-barefoot',
	host + '/fitness/articles/how-to-hit-a-punching-bag',
	host + '/fitness/articles/obstacle-course-race-training-wall-and-crawl',
	host + '/fitness/articles/upper-body-workouts-to-keep-you-toned-and-strong',
	host + '/running/articles/3-tips-for-increasing-your-race-distance',
	host + '/fitness/articles/body-composition-and-its-role-in-health',
	host + '/outdoors/articles/camping-with-dogs-101',
	host + '/running/articles/5-steps-to-proper-running-form',
	host + '/nutrition/articles/nutrition-performance-tips-for-endurance-athletes',
	host + '/fitness/articles/pregnancy-workouts-from-a-celebrity-trainer',
	host + '/fitness/articles/how-to-do-a-sit-up-the-right-way',
	host + '/fitness/articles/cardio-workouts-at-home-from-joe-decker',
	host + '/tennis/articles/how-to-add-topspin-to-your-ground-strokes',
	host + '/fitness/articles/squat-exercises-for-beginners',
	host + '/running/articles/5-things-runners-should-do-on-the-morning-after-race-day',
	host + '/fitness/articles/at-home-workouts-for-new-moms',
	host + '/fitness/articles/celebrity-workout-secrets-to-getting-the-perfect-butt',
	host + '/fitness/articles/shape-up-for-spring-5-waist-slimming-exercises',
	host + '/fitness/articles/slider-workout-to-strengthen-your-core-and-arms',
	host + '/triathlon/articles/strength-training-circuit-for-triathletes',
	host + '/fitness/articles/how-to-choose-a-pilates-class',
	host + '/outdoors/articles/how-to-protect-your-food-from-animals-while-camping',
	host + '/fitness/articles/how-to-cool-down-after-a-fitness-class',
	host + '/running/articles/nyc-marathon-course-tips',
	host + '/running/articles/how-fartlek-workouts-can-boost-your-running-tempo',
	host + '/fitness/articles/tabata-workout-for-the-arms-and-legs',
	host + '/running/articles/when-should-newbie-runners-increase-their-race-distance',
	host + '/fitness/articles/10-minute-workout-for-bikini-ready-abs',
	host + '/triathlon/articles/swimming-tips-from-a-pro-natalie-coughlin',
	host + '/running/articles/yoga-stretches-for-runners',
	host + '/tennis/articles/how-to-nail-your-approach-shot-every-time',
	host + '/running/articles/how-to-avoid-leg-cramps-on-marathon-race-day',
	host + '/swimming/articles/how-rebecca-soni-preps-for-the-olympics',
	host + '/tennis/articles/no-1-serving-drill-to-keep-your-ball-out-of-the-net',
	host + '/soccer/articles/soccer-player-s-guide-to-changing-direction',
	host + '/running/articles/how-to-find-a-running-form-that-s-right-for-you',
	host + '/nutrition/articles/how-to-create-a-summer-race-hydration-plan',
	host + '/fitness/articles/3-core-strengthening-exercises-for-women',
	host + '/fitness/articles/yoga-neck-stretches-to-boost-your-flexibility',
	host + '/tennis/articles/what-you-can-learn-from-andy-murray-s-serve',
	host + '/health/articles/how-to-avoid-hydration-mistakes-on-race-day',
	host + '/fitness/articles/at-home-workouts-made-simple',
	host + '/nutrition/articles/tips-for-running-in-hot-weather',
	host + '/tennis/articles/video-the-secret-to-roger-federer-s-backhand-volley',
	host + '/running/articles/runners-diet-tips-to-boost-performance',
	host + '/fitness/articles/mud-runs-video-training-tips-and-highlights',
	host + '/running/articles/how-casey-tibbs-preps-for-the-paralympics',
	host + '/triathlon/articles/triathlon-training-tips-from-dave-scott',
	host + '/fitness/articles/office-yoga-chair-twist',
	host + '/tennis/articles/how-to-put-power-into-your-serve',
	host + '/cycling/articles/how-to-stay-hydrated-during-a-cycling-race',
	host + '/running/articles/ultra-running-gear-must-haves',
	host + '/baseball/articles/video-develop-a-consistent-hitting-stroke',
	host + '/fitness/articles/hollywood-full-body-blast-workout',
	host + '/outdoors/articles/10-hiking-essentials-you-should-master',
	host + '/health/articles/aid-station-tips-for-marathoners',
	host + '/tennis/articles/how-to-add-power-to-your-one-handed-backhand',
	host + '/running/articles/5-stretches-for-runners-to-keep-you-injury-free',
	host + '/nutrition/articles/how-to-conquer-your-sugar-addiction',
	host + '/running/articles/how-newbie-runners-can-prepare-for-race-day',
	host + '/fitness/articles/3-kettlebell-exercises-to-boost-your-running-performance-part-two',
	host + '/triathlon/articles/get-ready-and-go-with-active-com',
	host + '/fitness/articles/cardio-yoga-workouts-runner-lunges',
	host + '/fitness/articles/injury-prevention-video-tips',
	host + '/tennis/articles/how-to-reduce-unforced-errors-937745',
	host + '/fitness/articles/your-bikini-body-workout-plan',
	host + '/outdoors/articles/how-to-hike-with-your-kids',
	host + '/running/articles/4-dynamic-warm-up-exercises-for-runners',
	host + '/fitness/articles/video-break-up-with-your-gym-escape-routine-and-overcome-obstacles',
	host + '/tennis/articles/how-to-dominate-the-net-in-singles',
	host + '/fitness/articles/how-to-do-pull-ups-correctly',
	host + '/tennis/articles/master-federer-s-forehand-step-3',
	host + '/fitness/articles/pre-natal-strength-training-workout',
	host + '/running/articles/how-much-fluid-do-you-need-as-a-runner',
	host + '/tennis/articles/the-key-to-a-killer-backhand-slice',
	host + '/running/articles/how-to-master-chi-running',
	host + '/cycling/articles/bike-maintenance-how-to-videos',
	host + '/fitness/articles/full-body-crossfit-workout',
	host + '/triathlon/articles/ironman-tips-from-dave-scott',
	host + '/fitness/articles/bikini-body-workout-in-10-minutes-or-less',
	host + '/running/articles/ultra-running-gear-essentials',
	host + '/running/articles/beginner-runners-and-the-aches-and-pains-of-running',
	host + '/fitness/articles/bikini-body-workout-for-the-winter-months',
	host + '/fitness/articles/the-ultimate-10-minute-butt-workout',
	host + '/cycling/articles/bike-repair-and-maintenance-tips-from-the-pros',
	host + '/fitness/articles/dumbbell-workouts-to-get-a-body-like-cameron-diaz',
	host + '/fitness/articles/new-mom-muscle-sculpting-workout',
	host + '/nutrition/articles/sports-nutrition-video-tips',
	host + '/running/articles/3-kettlebell-exercises-to-boost-running-performance',
	host + '/tennis/articles/the-key-to-flawless-topspin-ground-strokes',
	host + '/fitness/articles/jillian-michaels-kickbox-fastfix-workout',
	host + '/running/articles/8-ways-to-boost-your-running-injury-prevention',
	host + '/fitness/articles/strength-training-workouts-to-boost-your-fitness',
	host + '/fitness/articles/how-to-deal-with-post-workout-aches-and-pains',
	host + '/running/articles/3-video-tips-for-advanced-runners',
	host + '/fitness/articles/how-to-run-like-the-star-of-the-hunger-games',
	host + '/fitness/articles/the-chase-how-to-train-off-the-bike',
	host + '/running/articles/3-ways-marathoners-can-prepare-for-the-hills',
	host + '/baseball/articles/video-fundamentals-of-your-batting-stance',
	host + '/running/articles/how-to-run-at-the-beach',
	host + '/fitness/articles/how-to-work-your-abs-and-glutes-with-the-balance-lunge',
	host + '/triathlon/articles/how-to-plan-your-race-day-fuel',
	host + '/running/articles/treadmill-running-vs-outdoor-running',
	host + '/running/articles/video-tips-for-beginner-runners',
	host + '/tennis/articles/master-federer-s-forehand-step-1',
	host + '/fitness/articles/your-5-minute-cardio-mini-workout',
	host + '/running/articles/ultrarunning-video-tips',
	host + '/cycling/articles/century-ride-video-tips',
	host + '/fitness/articles/obstacle-course-race-training-push-ups',
	host + '/running/articles/tips-from-a-pro-matt-fitzgerald',
	host + '/tennis/articles/master-federer-s-forehand-step-2',
	host + '/fitness/articles/on-the-road-workouts-to-keep-you-fit',
	host + '/running/articles/3-ways-runners-can-get-a-strong-butt',
	host + '/running/articles/how-runners-can-benefit-from-a-shoe-fit',
	host + '/triathlon/articles/race-day-video-tips-for-triathletes',
	host + '/tennis/articles/when-to-use-the-windshield-wiper-forehand',
	host + '/fitness/articles/hamstring-curls-for-an-amazing-booty',
	host + '/nutrition/articles/hydration-gear-essentials-for-trail-running',
	host + '/fitness/articles/core-workouts-from-the-world-s-fittest-man',
	host + '/fitness/articles/5-pregnancy-pilates-exercises'
];

var errors = [];

async.eachSeries(urls, function (url, cb) {
	request.get({followRedirect: false, url: url }, function (error, response, body) {
		var expecteda = url.split('/');
		var expected = 'http://' + expecteda[2] + '/' + expecteda[3] + '/' + expecteda[4];
		if (response.headers.status !== '301') {
			errors.push({
				type: 'no redirect',
				url: url
			});
		} else if (expected !== response.headers.location) {
			errors.push({
				type: 'unexpected',
				url: url,
				redirectedTo: response.headers.location
			});
		}
		cb();
	});	
}, function (err) {
	if (err) {
		console.error(err);
	} else {
		console.info('all done');
		console.error(errors);
	}
});